"""first revision

Revision ID: ff69309758b6
Revises: 
Create Date: 2023-02-19 22:30:28.620053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff69309758b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'creator_userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('fk_event_user1_idx', table_name='event')
    op.drop_constraint('fk_event_user1', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['creator_userId'], ['userId'])
    op.alter_column('participant', 'user_userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participant', 'event_eventId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('participant', 'user_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_index('fk_user_has_event_event1_idx', table_name='participant')
    op.drop_index('fk_user_has_event_user_idx', table_name='participant')
    op.drop_constraint('fk_user_has_event_user', 'participant', type_='foreignkey')
    op.drop_constraint('fk_user_has_event_event1', 'participant', type_='foreignkey')
    op.create_foreign_key(None, 'participant', 'event', ['event_eventId'], ['eventId'])
    op.create_foreign_key(None, 'participant', 'user', ['user_userId'], ['userId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.create_foreign_key('fk_user_has_event_event1', 'participant', 'event', ['event_eventId'], ['eventId'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_user_has_event_user', 'participant', 'user', ['user_userId'], ['userId'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('fk_user_has_event_user_idx', 'participant', ['user_userId'], unique=False)
    op.create_index('fk_user_has_event_event1_idx', 'participant', ['event_eventId'], unique=False)
    op.alter_column('participant', 'user_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('participant', 'event_eventId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participant', 'user_userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('fk_event_user1', 'event', 'user', ['creator_userId'], ['userId'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('fk_event_user1_idx', 'event', ['creator_userId'], unique=False)
    op.alter_column('event', 'creator_userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
